# Generated by Django 5.2.17 on 2026-09-24 01:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('capacity', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(100)])),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=3000)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('resource', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=160)),
                ('contact', models.CharField(max_length=160)),
                ('product_name', models.CharField(max_length=160)),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('time', models.TimeField()),
                ('flavor', models.CharField(blank=True, max_length=300)),
                ('filling', models.CharField(blank=True, max_length=300)),
                ('theme', models.CharField(blank=True, max_length=500)),
                ('restrictions', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('cotizado', 'Cotizado'), ('confirmado', 'Confirmado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=16)),
                ('quote', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('quote_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept', models.CharField(max_length=300)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('date', models.DateField()),
                ('voided', models.BooleanField(default=False)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept', models.CharField(max_length=300)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('insumos', 'insumos'), ('costo_fijo', 'costo_fijo'), ('costo_variable', 'costo_variable'), ('otro', 'otro')], max_length=20)),
                ('voided', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.order')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 1), ('amount__lte', 999999999)), name='valid_expense_amount')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['day', 'status'], name='shop_order_day_id_2bfc87_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 100)), name='valid_quantity'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 1), ('amount__lte', 999999999)), name='valid_sale_amount'),
        ),
    ]
